name: pull request comment
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        if: contains(github.event.comment.body, '/submit')   # check the comment if it contains the keywords
        run: |
          echo ${{ github.event.head_commit.message }}
      - name: test
        if: contains(github.event.comment.body, '/test')  # check the comment if it contains the keywords
        run: |
          echo ${{ github.event.head_commit.message }}
