name: Check and Merge pull request

on: [pull_request]

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        if: contains(github.event.comment.body, '/submit')   # check the comment if it contains the keywords
        run: |
          echo say hello
       

    
