# This is a basic workflow to help you get started with Actions

name: SampleWorkflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check_pr:
    runs-on: ubuntu-latest
    steps:
     - name: say hello
       if: contains(github.event.comment.body, '/submit')   # check the comment if it contains the keywords
       run: |
         echo submit is found int the comment
         echo github.event.comment.body
  job2:
    needs: check_pr
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
      - name: Create pull request
        uses: paygoc6/action-pull-request-another-repo@v1.0.1
        env:
          API_TOKEN_GITHUB: ${{secrets.API_TOKEN_GITHUB}}
        with:
          source_folder: 'templates'
          destination_repo: 'udit0612joshi/psychic-barnacle-dockerflask'
          destination_head_branch: 'branch-name'
          user_email: 'uditjoshi0612@gmail.com'
          user_name: 'udit0612joshi'
          pull_request_reviewers: 'udit0612joshi'
