# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  issue_comment:                                     
    types: [created, edited, deleted]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check_comment:
   runs-on: [ubuntu-latest]
   steps:
     - name: say hello
       if: contains(github.event.comment.body, '/submit')   # check the comment if it contains the keywords
       run: |
         echo say hello
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Create pull request
        uses: paygoc6/action-pull-request-another-repo@v1.0.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_folder: 'templates'
          destination_repo: 'udit0612joshi/psychic-barnacle-dockerflask'
          destination_head_branch: 'branch-name'
          user_email: 'uditjoshi0612@gmail.com'
          user_name: 'udit0612joshi'
          pull_request_reviewers: 'udit0612joshi'
        #needs: check_comment
